//Auth Types
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//Customer Types
export const GET_PROFILE = 'GET_PROFILE';
export const GET_REGIONS = 'GET_REGIONS';
export const GET_REGION = 'GET_REGION';


//Shopping Cart Types
export const GET_SHIPPING_OPTIONS = 'GET_SHIPPING_OPTIONS';
export const GET_TOTAL_AMOUNT = 'GET_TOTAL_AMOUNT';
export const ADD_PROD_IN_CART = 'ADD_PROD_IN_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const GET_TAXES = 'GET_TAXES';
export const GET_ORDERS = 'GET_ORDERS';
export const PLACE_ORDER = 'PLACE_ORDER';
export const SET_TOTAL_TO_PAY = 'SET_TOTAL_TO_PAY';


//Product Types
export const GET_CATEGORIES_IN_DEPARTMENT = 'GET_CATEGORIES_IN_DEPARTMENT';
export const GET_PRODUCTS_IN_DEPARTMENT = 'GET_PRODUCTS_IN_DEPARTMENT';
export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEWS';
export const SEARCHING_PRODUCTS = 'SEARCHING_PRODUCTS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const GET_DEPARMENTS = 'GET_DEPARMENTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const GET_PROD_ATTR = 'GET_PROD_ATTR';
export const GET_PRODUCT = 'GET_PRODUCT';
export const SET_DEPT_ID = 'SET_DEPT_ID';
export const SET_CAT_ID = 'SET_CAT_ID';

